config/routes.rb
Rails.application.routes.draw do
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  root to: "main#index"

  get "sign_up", to: "registrations#new"
  post "sign_up", to: "registrations#create"

  get "password", to: "passwords#edit"
  patch "password", to: "passwords#update"
 
  get "sign_in", to: "sessions#new"
  post "sign_in", to: "sessions#create"

  delete "logout", to: "sessions#destroy"

  get "password/reset", to: "password_resets#new"
  post "password/reset", to: "password_resets#create"
  get "password/reset/edit", to: "password_resets#edit"
  patch "password/reset/edit", to: "password_resets#update"

  get "data", to: "data#index"
  post "data", to: "data#user"

  get "family", to: "family#index"
  post "family", to: "family#create"
  delete "family", to: "family#remove"
  get "family/edit", to: "family#edit"
  post "family/edit", to: "family#update"

  get "about", to: "about#index"

  # Defines the root path route ("/")
  # root "articles#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/current.rb
class Current < ActiveSupport::CurrentAttributes
    attribute :user
end

app/models/person.rb
class Person < ApplicationRecord
    validates :name, presence: true
    validates :position, presence: true
    validates :age, presence: true
end

app/models/user.rb
class User < ApplicationRecord
    has_secure_password

    validates :email, presence: true
end

app/controllers/about_controller.rb
class AboutController < ApplicationController
    def index
    end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
    before_action :set_current_user

    def set_current_user
        if session[:user_id]
            Current.user = User.find_by(id: session[:user_id])
        end
    end

    def require_user_logged_in!
        redirect_to sign_in_path, alert: "You must be logged in to do that" if Current.user.nil?
    end
end

app/controllers/data_controller.rb
class DataController < ApplicationController
    def index
        @a_string_of_words = "This is something in text"
        @everyone = Person.all.order("name ASC")
        @total_ages = 0
        for human in @everyone
            @total_ages += human.age
        end
    end
    def user
        @everyone = Person.all.order("name ASC")
        id = params[:id]
        @family_member = Person.find_by(id: id)
        puts "Clicked by #{@family_member.name}"
        flash[:notice] = "You submitted #{@family_member.name}!"
        redirect_to data_path
    end
end

app/controllers/family_controller.rb
class FamilyController < ApplicationController
    def index
        @a_string_of_words = "Family is loaded"
        puts @a_string_of_words
    end

    def create
        @family_member = Person.new(params.permit(:name.downcase, :position.downcase, :age))
        @family_member.save
        puts "******** #{@family_member.name} "
        redirect_to family_path
    end

    def remove
        puts "***** delete *****"
        id = params[:id]
        @family_member = Person.find_by(id: id)
        @family_member.delete
        redirect_to data_path
    end

    def edit
        @id = params[:id]
        @family_member = Person.find_by(id: @id)
    end

    def update
        @id = params[:id]
        @family_member = Person.find_by(id: @id)
        @family_member.update(params.permit(:name.downcase, :position.downcase, :age))
        redirect_to data_path
    end
end

app/controllers/main_controller.rb
class MainController < ApplicationController
    def index

    end
end

app/controllers/password_resets_controller.rb
class PasswordResetsController < ApplicationController
    def new
    end

    def create
        @user = User.find_by(email: params[:email])

        if @user.present?
            PasswordMailer.with(user: @user).reset.deliver_now
        end

        redirect_to root_path, notice: "If that account exists we sent you a link"
    end

    def edit
        @user = User.find_signed!(params[:token], purpose: "password_reset")
    rescue ActiveSupport::MessageVerifier::InvalidSignature
        redirect_to sign_in_path, notice: "Your link has expired"
    end

    def update
        @user = User.find_signed!(params[:token], purpose: "password_reset")
        if @user.update(params.require(:user).permit(:password, :password_confirmation))
            redirect_to sign_in_path, notice: "Password was successully changed, please log in"
        else
            redirect_to password_reset_edit_path, notice: "Passwords were not matched"
        end
    end
end

app/controllers/passwords_controller.rb
class PasswordsController < ApplicationController
    before_action :require_user_logged_in!

    def edit

    end

    def update
        if Current.user.update(password_params)
            redirect_to root_path, notice: "Password updated!"
        else
            redirect_to password_path, notice: "Passwords do not match"
        end
    end

    private

    def password_params
        params.require(:user).permit(:password, :password_confirmation)
    end
end

app/controllers/registrations_controller.rb
class RegistrationsController < ApplicationController
    def new
        @user = User.new
    end
    def create
        #flash[:notice] = "You submitted #{params[:user]}!"
        #puts "params are #{params[:user]}"
        #redirect_to root_path
        
        @user = User.new(user_params)
        if @user.save
            @user.save
            session[:user_id] = @user.id
            redirect_to root_path, notice: "You submitted #{params[:user]}!"
        else
            puts "That didn't work"
            redirect_to sign_up_path, alert: "That did not work #{@user.errors.full_messages}"
        end
    end

    private

    def user_params
        user_params = params.require(:user).permit(:email, :password, :password_confirmation)
    end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController

    def new

    end

    def create
        user = User.find_by(email: params[:email])
        if user.present? && user.authenticate(params[:password])
            session[:user_id] = user.id
            redirect_to root_path, notice: "Logged in successfully"
        else
            redirect_to sign_in_path, notice: "invalid email or password"
        end
    end

    def destroy
        session[:user_id] = nil
        redirect_to root_path, notice: "Logged out"
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/about/index.html.erb
<div class="d-flex align-items-center justify-content-center">
    <h1>All About It</h1>
</div>

app/views/data/index.html.erb
<div class="d-flex align-items-center justify-content-center">
    <h1>Let us look at some data</h1>
    
</div>
<div class="d-flex align-items-center justify-content-center">
<h2>The total age of everyone is <%= @total_ages %></h2>
</div>
<div class="container">
<div class="row justify-content-around gap-3">
<% @everyone.each do |thing| %>

    <div id="<%= thing.id %>" class="card" style="width: 18rem;">
    <div class="card-body">
    <h5 class="card-title"><%= thing.name.upcase %></h5>
    <h6 class="card-subtitle mb-2 text-muted"><%= thing.position.capitalize %></h6>
    <p class="card-text">They are <%= thing.age%> years old </p>
    <div class="row">
      <div class="col">
        <%= link_to "Edit", family_edit_path(id: thing.id), method: :edit, class: "btn btn-outline-primary btn-sm" %>
      </div>
      <div class="col">
        <%= button_to "Delete", family_path(id: thing.id), method: :delete, class: "btn btn-outline-danger btn-sm" %>
      </div>
    </div>
     
  </div>
</div>
<% end %>
</div>
</div>

app/views/family/edit.html.erb
<h1>Let's edit someone</h1>

<%= form_with model: @person, url: family_edit_path do |form| %>

    <div class="mb-3">
        <%= form.label :name %>
        <%= form.text_field :name, class: "form-control", placeholder: "Name", value: "#{@family_member.name.capitalize}" %>
        <%= form.hidden_field :id, class: "form-control", placeholder: "ID", value: "#{@family_member.id}" %>
    </div>

    <div class="mb-3">
        <%= form.label :position %>
        <%= form.text_field :position, class: "form-control", placeholder: "Position", value: "#{@family_member.position}" %>
    </div>

    <div class="mb-3">
        <%= form.label :age %>
        <%= form.number_field :age, class: "form-control", placeholder: "Age", value: "#{@family_member.age}" %>
    </div>

    <div class="mb-3">
        <%= form.submit class: "btn btn-primary" %>
    </div>

<% end %>

app/views/family/index.html.erb
<h1>We are family</h1>

<%= form_with model: @person, url: family_path do |form| %>

    <div class="mb-3">
        <%= form.label :name %>
        <%= form.text_field :name, class: "form-control", placeholder: "name" %>
    </div>

    <div class="mb-3">
        <%= form.label :position %>
        <%= form.text_field :position, class: "form-control", placeholder: "position" %>
    </div>

    <div class="mb-3">
        <%= form.label :age %>
        <%= form.number_field :age, class: "form-control", placeholder: "age" %>
    </div>

    <div class="mb-3">
        <%= form.submit class: "btn btn-primary" %>
    </div>

<% end %>

app/views/family/update.html.erb
<h1>Done updating someone</h1>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>ScheduledTweets</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-ka7Sk0Gln4gmtz2MlQnikT1wXgYsOg+OMhuP+IlRH9sENBO0LRn5q+8nbTov4+1p" crossorigin="anonymous"></script>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= render partial: "shared/navbar" %>

    <div class="container">
      <%= render partial: "shared/flash" %>
      <%= yield %>
    </div>
  </body>
</html>

app/views/main/index.html.erb
<div class="d-flex align-items-center justify-content-center">
    <h1>Welcome to FAMfam</h1>
</div>
<div class="d-flex align-items-center justify-content-center">
    <h2>A list of everyone in your family</h2>
</div>

app/views/password_resets/edit.html.erb
<h1>Reset your password</h1>

<%= form_with model: @user, url: password_reset_edit_path(token: params[:token]) do |form| %>
<% if form.object.errors.any? %>
        <div class="alert alert-danger">
            <% form.object.errors.full_messages.each do |message| %>
                <div><%= message %></div>
            <% end %>
        </div>
    <% end %>
    <div class="mb-3">
     <%= form.label :password %>
        <%= form.password_field :password, class: "form-control", placeholder: "password" %>
    </div>
    <div class="mb-3">
        <%= form.label :password_confirmation %>
        <%= form.password_field :password_confirmation, class: "form-control", placeholder: "password" %>
    </div>

    <div class="mb-3">
        <%= form.submit "Reset password", class: "btn btn-primary" %>
    </div>

<% end %>

app/views/password_resets/new.html.erb
<h1>Forgot your password?</h1>

<%= form_with url: password_reset_path do |form| %>

    <div class="mb-3">
        <%= form.label :email %>
        <%= form.text_field :email, class: "form-control", placeholder: "your.email@internet.com" %>
    </div>

    <div class="mb-3">
        <%= form.submit "Send email", class: "btn btn-primary" %>
    </div>

<% end %>

app/views/shared/_flash.html.erb
<% if flash[:notice] %>
    <div class="alert alert-info mt-4" role="alert">
        <%= flash[:notice] %>
    </div>
<% end %>

<% if flash[:alert] %>
    <div class="alert alert-warning mt-4" role="alert">
        <%= flash[:alert] %>    
    </div>
<% end %>

app/views/shared/_navbar.html.erb
<nav class="navbar navbar-expand-lg navbar-light bg-light">
  <div class="container-fluid">
     <%= link_to "FAMfam", root_path, class: "navbar-brand" %>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarNav">
      <ul class="navbar-nav">
        <li class="nav-item">
          <%= link_to "Home", root_path, class: "nav-link" %>
        </li>
        <% if Current.user %>
        <li>
            <%= link_to "Data", data_path, class: "nav-link" %>
        </li>
          <li class="nav-item">
            <%= link_to "Add", family_path, class: "nav-link" %>
        </li>
        <% end %>
        <% if !Current.user %>
        <li class="nav-item">
            <%= link_to "Sign Up", sign_up_path, class: "nav-link" %>
        </li>
        <% end %>
      </ul>

      <ul class="navbar-nav ms-auto mb-2 mb-lg-0">
        <% if Current.user %>
        <li class="nav-link"> 

        <%= link_to Current.user.email, password_path %>
        </li>
        <li class="nav-link">
        <%= button_to "Logout", logout_path, method: :delete, class: "btn btn-outline-primary btn-sm" %>
        </li>
        <% else %>
        <li class="nav-link">
        <%= link_to "Sign In", sign_in_path, class: "btn btn-outline-primary btn-sm" %>
        </li>
        <% end %>
      </ul>
    </div>
  </div>
</nav>